name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        run: echo "Configure GitHub metrics here."
